---
title: 参加者案内：ベイズ統計WS「心理学者のためのベイズ統計学」6/30＠専修大学
author: ~
date: '2018-06-25'
categories: []
tags: []
description: ''
thumbnail: ''
---


　この度は広島ベイズ塾主催・ベイズ統計WS「心理学者のためのベイズ統計学」にご参加くださりありがとうございます。  
  
　いよいよ開催が近づいてまいりました。皆様のご来場をお待ちいたしますとともに，会場周辺情報等をお知らせいたします。  
  
### 交通アクセス  
  
会場は専修大学生田キャンパス２号館，Lerning Studio211です。  
生田キャンパスへのアクセスは，[こちら](https://www.senshu-u.ac.jp/access.html)を，  
会場までは[キャンパスマップ](https://www.senshu-u.ac.jp/about/campus/ikuta.html)をよくご確認ください。  
  
電車でお越しいただく際は，向ヶ丘遊園駅（小田急線）北口にありますバス乗り場，２番からでます「専修大学前」あるいは「専修大学９号館」ゆきにお乗りいただき，終点の「専修大学前」で降りてください。  


### 受付について  
  
　会場では受付担当者にid(connpass登録名)か受け付け番号をお伝えください。

### 昼食について  
  
　会場周辺では，学食，カレー専門店，コンビニエンスストアをご利用いただけますが，昼食時間帯は混雑が予想されますので，事前にご準備いただくことをお勧めいたします。

### 会場環境について  
  
　6/30は大学の文化祭(黒門祭)が開催されています。多くの学生がキャンパス内にいることが想定されます。悪しからずご容赦ください。  
会場ではWi-Fi環境としてEduroamをご利用いただけます。  
  
### 質疑応答・事前アンケートについて  
  
　当日の質疑応答には，GoogleFormに質問を随時投稿していただくことができます。 質問の投稿は[こちら](https://goo.gl/forms/8f4vs1zKAqnZH1Kz1)からお願いいたします。　
事前に質問を投函していただいても構いません。  
  
また，Twitterアカウント@[bayesjuku](https://twitter.com/bayesjuku) でも情報発信をしておりますが，こちらのアカウントにメンションをいただいても結構です。  
当日，内容に関わるツイートをされる場合は，ハッシュタグ#bayesWS3rd をご利用ください。  

### 問い合わせ先  
  
　企画代表者・小杉考司　kosugi＠psy.senshu-u.ac.jp  
