---
title: ベイズ統計WS「心理学者のためのベイズ統計学」6/30＠専修大学（第一報）
author: ~
date: '2018-05-21'
slug: ws-6-30
categories: []
tags: []
description: ''
thumbnail: ''
---

広島ベイズ塾・第三回ワークショップ

「心理学者のためのベイズ統計学：モデリングの実際と，モデル選択・評価」のご案内（第一報）

広島ベイズ塾は，昨年の日本心理学会大会＠久留米で「心理学におけるベイズ統計モデリングの可能性」と題した公募シンポジウムを開催しました。限られた時間と場所では語りきれなかった内容を，今回の自主企画ワークショップで語ります。

ベイズ統計学を応用したモデリングは心理学でどう利用できるのか。昨今様々な書籍が出版され，「ベイズ統計学」の盛り上がりがあることはわかるが，さて実際，心理学の研究者にとってはどういった利点，利用方法があるのだろうか。また，実際にモデリングをこれから使っていきたい人は，なにを学べばいいのだろうか。こうした疑問を持っている人と一緒に，ベイズ統計モデリングの楽しさを共有したいと思っています。

参加は無料ですが会場の都合上定員があります。参加方法等，詳細は第二報をお待ちください。

　　記

日時：2018年6月30日(土) 10:00 〜 17:30

場所：専修大学サテライトキャンパス（向ヶ丘遊園）スタジオA

(https://www.senshu-u.ac.jp/social/satellite/)

企画代表：小杉考司（専修大学）

司会：紀ノ定保礼（静岡理工科大学）　

発表1.「はじめに：心理学における【ベイズ統計】の流行を整理する」
発表2.「これからの仮説評価・モデル選択の仕方：JASPなどを例に」
発表3.　ベイズモデリングの実践例
　1.認知心理学における事例
　2.臨床心理学における事例
　3.社会心理学における事例
　4.教育心理学における事例
発表4.「これからモデリングする人のための学びのルート」
　適宜質疑応答の時間や休憩をいれます

登壇予定者：※変更の可能性があります
　清水裕士（関西学院大学）　北條大樹（東京大学）　武藤拓之（大阪大学）　難波修史（広島大学）　徳岡大（高松大学）　杣取恵太（専修大学）　山根嵩史（川崎医療福祉大学）ほか

定員：50名
参加費用：無料
参加予約方法：ATNDなどのウェブサービスを利用予定(後日第二報にて，URLなどお伝えします)


